package com.connected.car.user.constants;


public class ResponseMessage {
	
	public static final String CREATE_MESSAGE="User Created Successfully";
	public static final String UPDATE_MESSAGE="User Details updated Successfully!";
	public static final String DELETE_MESSAGE="User deleted successfully";
	public static final String ACTIVATE_MESSAGE="User Status activated successfully";
	public static final String INACTIVATE_MESSAGE="User Status deactivated successfully";
	public static final String ACTIVE_MESSAGE="User Status is : ACTIVE";
	public static final String INACTIVE_MESSAGE="User Status is : INCTIVE";
	public static final String FETCHING_MESSAGE="Users details fetched successfully";
	public static final String ERROR_MESSAGE="An Error Occured:";
	//public static final String IDENTITY_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjcEhIaklwRldiMWtJNGg0bE5ENzhmcVVmbDk5LXhoN0Q4aER3UHRIX2xJIn0.eyJleHAiOjE3MDEyNTkzMzAsImlhdCI6MTcwMTI1OTAzMCwianRpIjoiMmUwMDMyOTktYTIwZS00ZTY2LWFmZmItM2I2YTY3ODU0OTRlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9jb25uZWN0ZWQtY2FycyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIwMTMwZDMyZi1kNzA2LTQ0ZmYtODY1NC1jNzMzZGU5MjA4NjAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ1c2VyQ2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjQwOTJlNzM1LTg0OGMtNDExMi04MTBlLTYzYWViYWQxMjcyYiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgzIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWNvbm5lY3RlZC1jYXJzIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjQwOTJlNzM1LTg0OGMtNDExMi04MTBlLTYzYWViYWQxMjcyYiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkRhcnNoYW4gTSBDIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGFyc2hhbiIsImdpdmVuX25hbWUiOiJEYXJzaGFuIiwiZmFtaWx5X25hbWUiOiJNIEMifQ.bgo3bJNYqSNE9PGmta4PmwX-tpB4LrjosLmrtbrwmsev1mbNIrieTYc8hn9xPV6enzQweIIPkp-PCh45N5jOjTk2QCTQ5GOlTUPjr55FEytUnShCFGaU7DPPsCH-iv1taGMSvxe_hPA1MH9fEsjTTWTwP-WlDg4NUi7oHQINcE2q2CvHKshaxS-zjrqrNpQ28oZaz-1V-iBERql700ESmj6TUgQzRwky-nGZUtAkGAaUcy-jDUrY994f5c9zM9rdx9UM4yochyyEzJp5E02LAcCdppPtjeob6CfQoNNmO0fyt7y7lun6voZ17wYBEeSI-qVRDbvWGQwrgnpSTe5sjw";

	private ResponseMessage()
	{
		
	}
}
